# The type of the AI service (openai or azure)
service: openai
# The API key for the AI service
api_key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# The organization ID for the AI service (optional for openai, required for azure)
org_id: org-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# The engine name for the AI service
engine: davinci
# The temperature parameter for the AI service
temperature: 0.9
# The top_p parameter for the AI service
top_p: 1
# The frequency_penalty parameter for the AI service
frequency_penalty: 0
# The presence_penalty parameter for the AI service
presence_penalty: 0
# The max_tokens parameter for the AI service
max_tokens: 512
# The stop parameter for the AI service
stop: "\n\n"
# The input directory containing the PDF files with the session notes
input_dir: input
# The output directory where the TSOAP notes will be written
output_dir: output
# The format of the output file name for each session note
tsoap_outfile: "{session_file}.tsoap"
# The format of the email document in the output file
email_doc: "Email document:\n{email_doc}"
# The format of the SOAP document in the output file
soap_doc: "SOAP document:\n{soap_doc}"
# The system prompt for the AI service
system_prompt: "This is a system that helps therapists process their therapy notes using the SOAP format. It also generates an email document that summarizes the session and provides recommendations for the next steps. The system takes a session note as input and outputs an email document and a SOAP document.\n\n"
# The session prompt for the AI service
session_prompt: "Session note:\n{session_note}\n\nPlease generate an email document and a SOAP document for this session note."
